CREATE TABLE Cart(
CustomerID INT NOT NULL,
AlbumID INT NOT NULL,
Qty INT NOT NULL,

FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (AlbumID) REFERENCES Album (AlbumID) ON UPDATE CASCADE ON DELETE CASCADE
)